### ISSUE TITLE
Why infrastructure has reference to application and not to Core?

### ISSUE THREAD

**Issue by dacanetdev** [mdemrulkayes/Quizzer#2]

**Comment by mdemrulkayes** [comment]
@dacanetdev If we look into the below Image of Clean Architecture then I found that the Core layer is protected by the Application layer and the Infrastructure layer is a reference to both the Application and Core. Usually, in other projects, I also make a reference from Infrastructure to Core but For this project, I made these changes based on the different Clean Arch. images and tried to explore if there were any problems I faced. It might be a violation of Clean Architecture. I'll change it later if required.

Thanks.

![image](https://github.com/mdemrulkayes/Quizzer/assets/9307157/f40304e1-16ac-49d7-afd0-dda45e72bc49)
